#!/bin/sh -e
assert_hihi() {
    actual="`bin/gitdirfromurl $@`"
    if [ hihi != "$actual" ]; then
        printf -e "\n\e[31m$@ became $actual\e[0m\n"
        exit 2
    else
        printf "\e[32m.\e[0m"
    fi
}
assert_hihi git@github.com:rking/hihi
assert_hihi git@github.com:rking/hihi.git
assert_hihi https://github.com/rking/hihi
assert_hihi https://github.com/rking/hihi
assert_hihi git@secrethost:hihi
assert_hihi /var/stuff/hihi
assert_hihi rking/hihi
assert_hihi git@github.com:rking/override_me hihi
echo; echo "L'champignon!!"
