#!/bin/sh -e
assert_hihi() {
    actual="`bin/gitdirfromurl $@`"
    if [ hihi != "$actual" ]; then
        echo -e "\n\e[31m$@ became $actual\e[0m"
        exit 2
    else
        echo -ne "\e[32m.\e[0m"
    fi
}
assert_hihi git@github.com:rking/hihi
assert_hihi git@github.com:rking/hihi.git
assert_hihi https://github.com/rking/hihi
assert_hihi https://github.com/rking/hihi
assert_hihi git@secrethost:hihi
assert_hihi /var/stuff/hihi
assert_hihi git@github.com:rking/override_me hihi
echo -e "\nL'champignon!!"
