#!/bin/sh
if type ,hub &> /dev/null; then
    # This is the one that ,hubi installs as a (faster) standalone
    git() { ,hub "$@"; }
    hub() { ,hub "$@"; }
elif type hub &> /dev/null; then
    git() { hub "$@"; }
else
    hub_blurb="[32m,hubi run — reexec your shell to get \`hub\` powers.[0m"
    if [ -n "$WANT_ALL" ]; then
        ,hubi && echo $hub_blurb
    else
        hub() {
            ,hubi && ,hub "$@"
            echo $hub_blurb
        }
    fi
fi
