#!/bin/zsh
local expected_zshgitprompt=~/.../src/zsh-git-prompt
if [[ ! -e $expected_zshgitprompt ]]; then
    echo "$expected_zshgitprompt empty."
    echo "https://github.com/olivierverdier/zsh-git-prompt needed ."
fi
local expected_gitdotsdir=~/.../src/git-dots
if [[ ! -d $expected_gitdotsdir/bin ]]; then
    [[ $PREEXEC_HUSHUP != 1 ]] &&
        echo "No bin/ dir in $expected_gitdotsdir; Odd."
    export PREEXEC_HUSHUP=1
fi

source $expected_zshgitprompt/zshrc.sh
export __GIT_PROMPT_DIR=$expected_zshgitprompt
PROMPT='$(git_super_status)%{$fg[cyan]%}%B%#%b%{${reset_color}%} '
RPROMPT='%{$fg[cyan]%}%n@%m%b:%{$fg[red]%}%B%~'

# The cache is more of a pain than a win.
function preexec_update_git_vars() { __EXECUTED_GIT_COMMAND=1 }
# set ft=zsh
